Support opening/closing luks encrypted ceph volumes
medallia/docker pull request #15
Opened 2017-03-13 20:23 UTC by axqx

Solves https://jira.medallia.com/browse/CIF-30

Tests:

1. Test mount ceph encrypted volume using docker

1.1. Manually create encrypted volume
```
rbd create lala-1 --size 16G
 sudo rbd map lala-1 
sudo cryptsetup luksFormat /dev/rbd0 # lala-1
cryptsetup luksOpen /dev/rbd0 lala-1 
mkfs.ext4 /dev/mapper/lala-1
mkdir /vagrant/data/lala-1 
mount /dev/mapper/lala-1 /vagrant/data/lala-1
echo "dog" > /vagrant/data/lala-1/cat
```

1.2. Mount volume with docker container
```
medallia@fib-r10-u08:~$ docker run -ti -v lala-1:/foo:ceph,rw ubuntu /bin/bash
root@90f91393252d:/# cat /foo/cat 
dog
```

2. Test can't mount same ceph encrypted volume with docker twice

2.1 Try to run second container while one is still running
```
medallia@fib-r10-u01:~$ docker run -ti -v lala-1:/foo:ceph,rw ubuntu /bin/bash
docker: Error response from daemon: Failed to map Ceph volume 'lala-1': exit status 1 - (2460) Map lala-1
(2460) Map lala-1 failed: image is being watched: watcher=10.112.10.34:0/1093050966 client.114105 cookie=8.
```

2.2 kill first container and then re-run

```
medallia@fib-r10-u01:~$ docker run -ti -v lala-1:/foo:ceph,rw ubuntu /bin/bash
root@ef23c13041e8:/# cat /foo/cat 
dog
```

3. hard power-cycle machine while docker container with encrypted volume is running and try to re-mount volume on docker container in another machine 

This works in FIB but I had to manually remove locks and watchers for the volume since FIB is not doing this automatically. Will test in Germany.

2017-03-13 20:51 UTC, thorvald requested changes

2017-03-13 20:51 UTC, thorvald commented on volume/ceph/ceph.go
> +	criptoLUKS        = "crypto_LUKS"
Typo: Crypto

2017-03-13 20:51 UTC, thorvald commented on volume/ceph/ceph.go
> +		cmd = exec.Command("cryptsetup", "luksOpen", v.mappedDevicePath, v.Name())
Let's be nice to cryptsetup, and pass "-q" so it knows we're in batch mode. You might also want to pass "--key-file=-" to explicitly get the key from stdin in a programmatic way.

2017-03-13 20:51 UTC, thorvald commented on volume/ceph/ceph.go
>  	if fsType == "" {
Before we get here, we need to recheck the fsType, but now checking it from the opened volume. We do want to run fsck etc on the opened cryptovolume.

2017-03-14 00:12 UTC, axqx commented on volume/ceph/ceph.go
> +		cmd = exec.Command("cryptsetup", "luksOpen", v.mappedDevicePath, v.Name())
Added "--key-file=-", --batch-mode is not relevant for luksOpen:

```--batch-mode, -q
Do not ask for confirmation. Use with care! This option is only relevant for luksFormat, luksAddKey, luksRemoveKey or luksKillSlot.```

2017-03-14 00:13 UTC, axqx commented on volume/ceph/ceph.go
> +	criptoLUKS        = "crypto_LUKS"
Fixed in https://github.com/medallia/docker/pull/15/commits/e2be6b11bf90ac40363bb3e4c80a28503acbed0c.

2017-03-14 00:14 UTC, axqx commented on volume/ceph/ceph.go
>  	if fsType == "" {
Fixed in https://github.com/medallia/docker/pull/15/commits/e2be6b11bf90ac40363bb3e4c80a28503acbed0c

2017-03-14 00:58 UTC, axqx commented
@thorvald, thank you for the comments. Updates added in https://github.com/medallia/docker/pull/15/commits/a10170555e5c350567eb59e9539beadb59721237

2017-03-15 21:08 UTC, mauri requested changes

2017-03-15 21:08 UTC, mauri commented on volume/ceph/ceph.go
> +		//if fsType == "" {
remove?

2017-03-15 21:08 UTC, mauri commented on volume/ceph/ceph.go
> +	if fsType == "crypto_LUKS" {
use the constant you extracted

2017-03-15 21:08 UTC, mauri commented on volume/ceph/ceph.go
> +	mappedDevicePath = v.mappedDevicePath
rename to deviceToMount to avoid confusions with v.mappedDevicePath?

2017-03-15 21:08 UTC, mauri commented on volume/ceph/ceph.go
> +	cryptoLUKS        = "crypto_LUKS"
cryptoLuksFsType? I think consts uses Uppercase?

2017-03-15 21:08 UTC, mauri commented on volume/ceph/ceph.go
>  	if fsType == "" {
else if?

2017-03-15 21:59 UTC, thorvald commented on volume/ceph/ceph.go
>  	if fsType == "" {
We want a straight if; If the image is luks encrypted, but does NOT have a filesystem, we want to create a filesystem after we lukeOpen the image.

2017-03-15 21:59 UTC, thorvald approved these changes

2017-03-15 22:00 UTC, thorvald commented
My requested changes look good; address Mauri's too and we should be GTG.

2017-03-15 22:01 UTC, mauri commented on volume/ceph/ceph.go
>  	if fsType == "" {
didn't see the overriding fsType inside the if block

2017-03-16 00:41 UTC, axqx commented on volume/ceph/ceph.go
> +	cryptoLUKS        = "crypto_LUKS"
Fixed in https://github.com/medallia/docker/pull/15/commits/975c9c2ab2e543bd69892b3254de4e3e90c1156e

2017-03-16 00:42 UTC, axqx commented on volume/ceph/ceph.go
> +	mappedDevicePath = v.mappedDevicePath
Fixed in https://github.com/medallia/docker/pull/15/commits/975c9c2ab2e543bd69892b3254de4e3e90c1156e.

2017-03-16 00:42 UTC, axqx commented on volume/ceph/ceph.go
> +		//if fsType == "" {
Fixed in https://github.com/medallia/docker/pull/15/commits/975c9c2ab2e543bd69892b3254de4e3e90c1156e

2017-03-16 00:42 UTC, axqx commented on volume/ceph/ceph.go
> +	if fsType == "crypto_LUKS" {
Fixed in https://github.com/medallia/docker/pull/15/commits/975c9c2ab2e543bd69892b3254de4e3e90c1156e

2017-03-16 00:45 UTC, axqx commented
@mauri commit https://github.com/medallia/docker/pull/15/commits/975c9c2ab2e543bd69892b3254de4e3e90c1156e addressed your comments. If you don't have additional comments and this looks good to you could you merge the PR please?

2017-03-16 15:41 UTC, mauri approved these changes

2017-03-16 15:42 UTC, merged